### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [duckie/boson#1]
Would you like to [replace any double quotes](https://github.com/duckie/boson/blob/c85917711f7dcf72c82b99a8b46cac1f07bdbf91/src/boson/boson/boson.h#L10 "Check inclusion style") by [angle brackets around file names for include statements](https://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by duckie** [comment]
Hi elfring !

I did not intend to in the first place. The actual policy is:
- Internal includes that are relative to each other (which is the case for your example) use double quotes.
- External excludes that are expected to be found in the include directories (third parties, system includes) use angle brackets.

This is meant the materialize the difference between an include from the project itself and an include expected from somewhere else. I we replace by angle brackets everywhere, all includes shall be prefixed by `boson/`.

There is an issue about `fmtlib` on this part, which will be fixed soon.

Do you have any technical reasons to replace them ? The only one I could see is replacing those headers by mocks, but we are not there yet.

**Comment by elfring** [comment]
I suggest to reconsider the consequences of [the following wording](http://c0x.coding-guidelines.com/6.10.2.html "Source file inclusion") from [the section “16.2 Source file inclusion”](http://open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf "Draft for the C++ standard specification") in the standard specification for the programming language “C++”.

```
…
The named source file is searched for in an implementation-defined manner. If this search is not supported, or if the search fails, the directive is reprocessed as if it read

#include <h-char-sequence> new-line
…
```
- How do you think about to avoid “a duplicated file search” here?
- Would you like to [restrict the searched directories](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html "Description for include syntax") for header files of your software?

**Comment by duckie** [comment]
Both are "implementation-defined".

The usual understanding of them is double quotes for headers owned by the project and angle brackets for the others, as stated by your own link.

This is is definitely not an issue since any of the compilers modern enough to compile that C++14 code have a well-defined and well-known behavior about it.

So, no change will be made to it while this is not a show-stopper for any planned feature.

Thank you very much for your input though 👍

**Comment by elfring** [comment]
There are different opinions about the handling of the involved implementation-defined behaviour.
- Will header files be also searched outside the specified include directories if double quotes are used for the discussed preprocessor statement?
- Is there a speed difference measurable if a file is not found there and the search will be retried with “the angle brackets inclusion method”?
